termination_positions_list:
- - 2.40 # 1.30 worksX-Coordinate (m from the origin)
  - 0.46 #Y-Coordinate (m from the origin)
  - 270 #Pose in Degrees (north is 0)

#- - 2.10 #X-Coordinate (m from the origin)
#  - 1.65 #Y-Coordinate (m from the origin)
#  - 270 #Pose in Degrees (north is 0)
