termination_positions_list:
- - 1.35 # 1.30 worksX-Coordinate (m from the origin)
  - 1.95 #Y-Coordinate (m from the origin)
  - 180 #Pose in Degrees (north is 0)
- - 1.6 # 1.30 worksX-Coordinate (m from the origin)
  - 0.95 #Y-Coordinate (m from the origin)
  - 0 #Pose in Degrees (north is 0)
- - 2.15 # 1.30 worksX-Coordinate (m from the origin)
  - 3.35 #Y-Coordinate (m from the origin)
  - 270 #Pose in Degrees (north is 0)
#- - 1 #X-Coordinate (m from the origin)
#  - 1.3 #Y-Coordinate (m from the origin)
#  - 90 #Pose in Degrees (north is 0)
