watchtowers_list:
- watchtower101
- watchtower102
- watchtower103
- watchtower104
- watchtower105
- watchtower106
- watchtower107
- watchtower108
- watchtower109
- watchtower110
- watchtower111
- watchtower112
